### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by lfraile** [lfraile-git-school/caption-this-shell#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by lfrailefree** [comment]
Hi there!

**Comment by MattDowningShell** [comment]
Hi

**Comment by marcialgarza** [comment]
Hello!

**Comment by VadimShpakovsky** [comment]
Hi guys!

**Comment by giulio-bellizia** [comment]
Hello there!

**Comment by cympatic** [comment]
Hi there!

**Comment by ArjunSingh05** [comment]
Hi !

**Comment by vatsalabangera2022** [comment]
Hello!

**Comment by Ozystar117** [comment]
Hi

**Comment by Suseela123-TW** [comment]
Hi

**Comment by achild5** [comment]
Hello!

**Comment by mling2022** [comment]
Hi from Meng

**Comment by PrasadSalimath** [comment]
Commenting for collab

**Comment by Monali-shell** [comment]
Hi there

**Comment by debasisyours** [comment]
Hi there!

**Comment by maheshkumarra** [comment]
Hi There

**Comment by sridhar-nalla** [comment]
Hi
